/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.admDAO;
import dto.adm_cadfornecedorDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanabe
 */
public class adm_cadfornecedorVIEW extends javax.swing.JFrame {

    /**
     * Creates new form adm_cadusuarioVIEW
     */
    public adm_cadfornecedorVIEW() {
        initComponents();
        setLocationRelativeTo(null);
        txtId.setVisible(false);
        listarFornecedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_dados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFornecedor = new javax.swing.JTable();
        btncarregarCampo = new javax.swing.JButton();
        jLabel_cadfornecedor = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_dados.setBackground(new java.awt.Color(255, 251, 251));
        jPanel_dados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel_dados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nome");
        jPanel_dados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Cnpj");
        jPanel_dados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Endereço");
        jPanel_dados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Telefone");
        jPanel_dados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("E-mail");
        jPanel_dados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel_dados.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 25));
        jPanel_dados.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, 25));
        jPanel_dados.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 25));
        jPanel_dados.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, 25));
        jPanel_dados.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 250, 25));

        txtId.setEditable(false);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel_dados.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 40, -1));

        getContentPane().add(jPanel_dados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 300, 290));

        btnEditar.setText("Editar");
        btnEditar.setPreferredSize(new java.awt.Dimension(70, 24));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 380, 90, 35));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 90, 35));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 90, 35));

        tabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CNPJ", "ENDEREÇO", "TELEFONE", "E-MAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFornecedor.setShowGrid(true);
        jScrollPane2.setViewportView(tabelaFornecedor);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 580, 430));

        btncarregarCampo.setText("Carregar Campos");
        btncarregarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarregarCampoActionPerformed(evt);
            }
        });
        getContentPane().add(btncarregarCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 520, -1, 35));

        jLabel_cadfornecedor.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel_cadfornecedor.setForeground(new java.awt.Color(244, 249, 252));
        jLabel_cadfornecedor.setText("Cadastro de Fornecedor");
        getContentPane().add(jLabel_cadfornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 40));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 430, 90, 35));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 90, 35));

        background.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        cadastrarFornecedor();
        limparCampos();
        listarFornecedor();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        alteraFornecedor();
        limparCampos();
        listarFornecedor();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btncarregarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarregarCampoActionPerformed
        carregarCampos();
    }//GEN-LAST:event_btncarregarCampoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        deletarDados();
        limparCampos();
        listarFornecedor();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adm_cadfornecedorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adm_cadfornecedorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adm_cadfornecedorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adm_cadfornecedorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adm_cadfornecedorVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btncarregarCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_cadfornecedor;
    private javax.swing.JPanel jPanel_dados;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaFornecedor;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void cadastrarFornecedor() {

        String nome, cnpj, endereco, telefone, email;

        nome = txtNome.getText();
        cnpj = txtCnpj.getText();
        endereco = txtEndereco.getText();
        telefone = txtTelefone.getText();
        email = txtEmail.getText();

        adm_cadfornecedorDTO objcadfornecedordto = new adm_cadfornecedorDTO();
        objcadfornecedordto.setNome(nome);
        objcadfornecedordto.setCnpj(cnpj);
        objcadfornecedordto.setEndereco(endereco);
        objcadfornecedordto.setTelefone(telefone);
        objcadfornecedordto.setEmail(email);

        admDAO objadmdao = new admDAO();
        objadmdao.cadfornecedorDAO(objcadfornecedordto);

    }

    private void limparCampos() {
        txtId.setText("");
        txtNome.setText("");
        txtCnpj.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtNome.requestFocus();

    }

    private void listarFornecedor() {

        try {

            admDAO objadmdao = new admDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFornecedor.getModel();
            model.setNumRows(0);

            ArrayList<adm_cadfornecedorDTO> listaf = objadmdao.pesquisarFornecedor();

            for (int num = 0; num < listaf.size(); num++) {

                model.addRow(new Object[]{
                    listaf.get(num).getId_fornecedor(),
                    listaf.get(num).getNome(),
                    listaf.get(num).getCnpj(),
                    listaf.get(num).getEndereco(),
                    listaf.get(num).getTelefone(),
                    listaf.get(num).getEmail()
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "adm_cadfornecedorVIEW - listarFornecedor: " + erro);
        }
    }

    private void carregarCampos() {

        int setar = tabelaFornecedor.getSelectedRow();
 
        txtId.setText(tabelaFornecedor.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tabelaFornecedor.getModel().getValueAt(setar, 1).toString());
        txtCnpj.setText(tabelaFornecedor.getModel().getValueAt(setar, 2).toString());
        txtEndereco.setText(tabelaFornecedor.getModel().getValueAt(setar, 3).toString());
        txtTelefone.setText(tabelaFornecedor.getModel().getValueAt(setar, 4).toString());
        txtEmail.setText(tabelaFornecedor.getModel().getValueAt(setar, 5).toString());

    }

    private void alteraFornecedor() {

        String nome_fornecedor, cnpj_fornecedor, endereco_fornecedor, telefone_fornecedor, email_fornecedor;
        int id_fornecedor;

        id_fornecedor = Integer.parseInt(txtId.getText());
        nome_fornecedor = txtNome.getText();
        cnpj_fornecedor = txtCnpj.getText();
        endereco_fornecedor = txtEndereco.getText();
        telefone_fornecedor = txtTelefone.getText();
        email_fornecedor = txtEmail.getText();

        adm_cadfornecedorDTO objcadfornecedordto = new adm_cadfornecedorDTO();
        objcadfornecedordto.setId_fornecedor(id_fornecedor);
        objcadfornecedordto.setNome(nome_fornecedor);
        objcadfornecedordto.setCnpj(cnpj_fornecedor);
        objcadfornecedordto.setEndereco(cnpj_fornecedor);
        objcadfornecedordto.setTelefone(nome_fornecedor);
        objcadfornecedordto.setEmail(email_fornecedor);

        admDAO objadmdao = new admDAO();
        objadmdao.alterarFornecedor(objcadfornecedordto);
    }

    private void deletarDados() {

        int id_fornecedor;

        id_fornecedor = Integer.parseInt(txtId.getText());

        adm_cadfornecedorDTO objcadfornecedordto = new adm_cadfornecedorDTO();
        objcadfornecedordto.setId_fornecedor(id_fornecedor);

        admDAO objadmdao = new admDAO();
        objadmdao.deletarFornecedor(objcadfornecedordto);
    }

}
