/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.conexaoDAO;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author nanabe
 */
public class adm_produtoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form adm_prodadd
     */
    public adm_produtoVIEW() {
        initComponents();
        setLocationRelativeTo(null);
    }

    String nome, quantidade;
    int cod;

    Connection conn;
    PreparedStatement pstm;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Data = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel_Produto = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel_Quantidade = new javax.swing.JLabel();
        txtQntd = new javax.swing.JTextField();
        jLabel_Cod = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtProd = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" Produto");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Data.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel_Data.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Data.setText("Data:");
        getContentPane().add(jLabel_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btnAdd.setBackground(new java.awt.Color(241, 255, 129));
        btnAdd.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 30));

        jLabel_Produto.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel_Produto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Produto.setText("Produto:");
        getContentPane().add(jLabel_Produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 84, -1));
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        jLabel_Quantidade.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel_Quantidade.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Quantidade.setText("Quantidade:");
        getContentPane().add(jLabel_Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        txtQntd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntdActionPerformed(evt);
            }
        });
        getContentPane().add(txtQntd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 30));

        jLabel_Cod.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel_Cod.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Cod.setText("Cod.Prod.:");
        getContentPane().add(jLabel_Cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
        });
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 100, 30));
        getContentPane().add(txtProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 30));

        btnLimpar.setBackground(new java.awt.Color(241, 255, 129));
        btnLimpar.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 30));

        btnVoltar.setBackground(new java.awt.Color(241, 255, 129));
        btnVoltar.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BACKGROUND-3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            cod = Integer.parseInt(txtCod.getText());

            String sql = "select nome_produto, quantidade_produto from adm_produto where id_produto = ?";
            conn = new conexaoDAO().conectaBD();

            try {
                pstm = conn.prepareStatement(sql);
                pstm.setInt(1, cod);
                rs = pstm.executeQuery();

                if (rs.next() == false) {

                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");

                } else {

                    nome = rs.getString("nome_produto");
                    quantidade = rs.getString("quantidade_produto");
                    txtProd.setText(nome.trim());
                }
            } catch (Exception erro) {

                JOptionPane.showMessageDialog(null, "adm_prodadd - txtCodKeyPressed: " + erro);
            }
            
            

        }
        
        

    }//GEN-LAST:event_txtCodKeyPressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        int qntd = Integer.parseInt(txtQntd.getText());
        int quant = Integer.parseInt(quantidade);
        int soma;

        soma = qntd + quant;
        
        String data, produto, quantidades;
        data = txtData.getText();
        produto = txtProd.getText();
        quantidades = String.valueOf(qntd);
        
        String sqli = "insert into adm_est (data_est, produto_est, quantidade) values (?,?,?)";
        conn = new conexaoDAO().conectaBD();
        
        try {
            pstm = conn.prepareStatement(sqli);
            pstm.setString(1, data);
            pstm.setString(2, produto);
            pstm.setString(3,quantidades);

            pstm.execute();
            pstm.close();
            
           

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "adm_prodadd - Insert add: " + e);
        }
        
        String sql = "UPDATE adm_produto set quantidade_produto = ? where id_produto = ?";
        conn = new conexaoDAO().conectaBD();

        try {
            pstm = conn.prepareStatement(sql);
            pstm.setInt(1, soma);
            pstm.setInt(2, cod);

            pstm.execute();
            pstm.close();
            

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "adm_prodadd - btnAdd: " + e);
        }
        
        dispose();

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtQntdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQntdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adm_produtoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adm_produtoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adm_produtoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adm_produtoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adm_produtoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Cod;
    private javax.swing.JLabel jLabel_Data;
    private javax.swing.JLabel jLabel_Produto;
    private javax.swing.JLabel jLabel_Quantidade;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtProd;
    private javax.swing.JTextField txtQntd;
    // End of variables declaration//GEN-END:variables

private void limparCampos(){
    
    txtCod.setText("");
    txtData.setText("");
    txtProd.setText("");
    txtQntd.setText("");
    
    txtData.requestFocus();
    
    
}


}
