/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.admDAO;
import dto.adm_controlDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanabe
 */
public class adm_fincontrolecaixaVIEW extends javax.swing.JFrame {

    /**
     * Creates new form adm_fincontrolecaixaVIEW
     */
    public adm_fincontrolecaixaVIEW() {
        initComponents();
        setLocationRelativeTo(null);
        listarControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaControl = new javax.swing.JTable();
        btninserirProdutos = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Caixa ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaControl.setBackground(new java.awt.Color(255, 255, 255));
        tabelaControl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "TIPO", "DESCRIÇÃO", "VALOR", "FUNCIONARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaControl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 920, 360));

        btninserirProdutos.setBackground(new java.awt.Color(255, 255, 255));
        btninserirProdutos.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btninserirProdutos.setForeground(new java.awt.Color(0, 0, 0));
        btninserirProdutos.setText("Inserir Contas");
        btninserirProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninserirProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(btninserirProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 150, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/template2.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninserirProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninserirProdutosActionPerformed
        adm_fincontrolecaixawndVIEW objfincontrolecaixawnd = new adm_fincontrolecaixawndVIEW();
        objfincontrolecaixawnd.setVisible(true);
    }//GEN-LAST:event_btninserirProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adm_fincontrolecaixaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adm_fincontrolecaixaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adm_fincontrolecaixaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adm_fincontrolecaixaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adm_fincontrolecaixaVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btninserirProdutos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaControl;
    // End of variables declaration//GEN-END:variables

    public void listarControl() {

        try {

            admDAO objadmdao = new admDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaControl.getModel();
            model.setNumRows(0);

            ArrayList<adm_controlDTO> listac = objadmdao.pesquisarControl();

            for (int num = 0; num < listac.size(); num++) {

                model.addRow(new Object[]{
                    listac.get(num).getData(),
                    listac.get(num).getTipo(),
                    listac.get(num).getDescricao(),
                    listac.get(num).getValor(),
                    listac.get(num).getFuncionario()

                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "adm_fincontrolecaixaVIEW - listarControl: " + erro);
        }
    }

}
