/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nanabe
 */
public class adm_telaprincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form adm_telaprincipalVIEW
     */
    public adm_telaprincipalVIEW() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        background = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        jMCadastro = new javax.swing.JMenu();
        jmFornecedor = new javax.swing.JMenuItem();
        jmProduto = new javax.swing.JMenuItem();
        jmUsuario = new javax.swing.JMenuItem();
        jMEstoque = new javax.swing.JMenu();
        jmES = new javax.swing.JMenuItem();
        jMFinanceiro = new javax.swing.JMenu();
        jmControleCaixa = new javax.swing.JMenuItem();
        jMRelatorio = new javax.swing.JMenu();
        jmVendas = new javax.swing.JMenuItem();
        jMSair = new javax.swing.JMenu();
        jmExit = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        MenuPrincipal.setPreferredSize(new java.awt.Dimension(500, 30));

        jMCadastro.setText("Cadastro");
        jMCadastro.setPreferredSize(new java.awt.Dimension(100, 19));

        jmFornecedor.setText("Fornecedor");
        jmFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFornecedorActionPerformed(evt);
            }
        });
        jMCadastro.add(jmFornecedor);

        jmProduto.setText("Produto");
        jmProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProdutoActionPerformed(evt);
            }
        });
        jMCadastro.add(jmProduto);

        jmUsuario.setText("Usuario");
        jmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioActionPerformed(evt);
            }
        });
        jMCadastro.add(jmUsuario);

        MenuPrincipal.add(jMCadastro);

        jMEstoque.setText("Estoque");
        jMEstoque.setPreferredSize(new java.awt.Dimension(100, 19));
        jMEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEstoqueActionPerformed(evt);
            }
        });

        jmES.setText("Entrada e Saída");
        jmES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmESActionPerformed(evt);
            }
        });
        jMEstoque.add(jmES);

        MenuPrincipal.add(jMEstoque);

        jMFinanceiro.setText("Financeiro");
        jMFinanceiro.setPreferredSize(new java.awt.Dimension(100, 19));

        jmControleCaixa.setText("Controle de Caixa");
        jmControleCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmControleCaixaActionPerformed(evt);
            }
        });
        jMFinanceiro.add(jmControleCaixa);

        MenuPrincipal.add(jMFinanceiro);

        jMRelatorio.setText("Relatórios");
        jMRelatorio.setPreferredSize(new java.awt.Dimension(100, 19));

        jmVendas.setText("Venda");
        jmVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVendasActionPerformed(evt);
            }
        });
        jMRelatorio.add(jmVendas);

        MenuPrincipal.add(jMRelatorio);

        jMSair.setText("Sair");
        jMSair.setPreferredSize(new java.awt.Dimension(100, 19));
        jMSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSairActionPerformed(evt);
            }
        });

        jmExit.setText("Fechar o Sistema");
        jmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExitActionPerformed(evt);
            }
        });
        jMSair.add(jmExit);

        MenuPrincipal.add(jMSair);

        setJMenuBar(MenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFornecedorActionPerformed
        adm_cadfornecedorVIEW objcadfornecedor = new adm_cadfornecedorVIEW();
        objcadfornecedor.setVisible(true);
    }//GEN-LAST:event_jmFornecedorActionPerformed

    private void jmProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProdutoActionPerformed
        adm_cadprodutoVIEW objcadproduto = new adm_cadprodutoVIEW();
        objcadproduto.setVisible(true);
    }//GEN-LAST:event_jmProdutoActionPerformed

    private void jmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioActionPerformed
        adm_cadusuarioVIEW objcadusuario = new adm_cadusuarioVIEW();
        objcadusuario.setVisible(true);
    }//GEN-LAST:event_jmUsuarioActionPerformed

    private void jMEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEstoqueActionPerformed

    }//GEN-LAST:event_jMEstoqueActionPerformed

    private void jMSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSairActionPerformed

    }//GEN-LAST:event_jMSairActionPerformed

    private void jmESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmESActionPerformed
        adm_estprodutoVIEW objestproduto = new adm_estprodutoVIEW();
        objestproduto.setVisible(true);
    }//GEN-LAST:event_jmESActionPerformed

    private void jmControleCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmControleCaixaActionPerformed
        adm_fincontrolecaixaVIEW objfincontrolecaixa = new adm_fincontrolecaixaVIEW();
        objfincontrolecaixa.setVisible(true);
    }//GEN-LAST:event_jmControleCaixaActionPerformed

    private void jmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExitActionPerformed
       
        LoginVIEW obj = new LoginVIEW();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmExitActionPerformed

    private void jmVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVendasActionPerformed
        adm_relvendasVIEW objrelvendas = new adm_relvendasVIEW();
        objrelvendas.setVisible(true);
    }//GEN-LAST:event_jmVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adm_telaprincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adm_telaprincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adm_telaprincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adm_telaprincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adm_telaprincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JLabel background;
    private javax.swing.JMenu jMCadastro;
    private javax.swing.JMenu jMEstoque;
    private javax.swing.JMenu jMFinanceiro;
    private javax.swing.JMenu jMRelatorio;
    private javax.swing.JMenu jMSair;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jmControleCaixa;
    private javax.swing.JMenuItem jmES;
    private javax.swing.JMenuItem jmExit;
    private javax.swing.JMenuItem jmFornecedor;
    private javax.swing.JMenuItem jmProduto;
    private javax.swing.JMenuItem jmUsuario;
    private javax.swing.JMenuItem jmVendas;
    // End of variables declaration//GEN-END:variables
}
