/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.conexaoDAO;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanabe
 */
public class atn_vendasVIEW extends javax.swing.JFrame {

    /**
     * Creates new form atn_vendasVIEW
     */
    public atn_vendasVIEW() {
        initComponents();
        setLocationRelativeTo(null);
    }

    Connection conn;
    PreparedStatement pstm;
    ResultSet rs;

    int code, cod, qntdS;
    String vt, dt, total;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_dados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        spnQntd = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelPagamento = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVenda = new javax.swing.JTable();
        jLabelTroco = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtPagamento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtExtrato = new javax.swing.JTextArea();
        btnRealizarVenda = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_dados.setBackground(new java.awt.Color(255, 255, 255));
        Panel_dados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_dados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cod. Prod.:");
        Panel_dados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
        });
        Panel_dados.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nome Prod.:");
        Panel_dados.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));
        Panel_dados.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 100, 30));

        spnQntd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQntdStateChanged(evt);
            }
        });
        Panel_dados.add(spnQntd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 50, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Qntd:");
        Panel_dados.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Preço:");
        Panel_dados.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        Panel_dados.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Valor:");
        Panel_dados.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 20));
        Panel_dados.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, 30));

        btnAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        Panel_dados.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 110, 40));
        Panel_dados.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Data:");
        Panel_dados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        getContentPane().add(Panel_dados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 610, 170));

        jLabelPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPagamento.setText("PAGAMENTO");
        getContentPane().add(jLabelPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 80, -1));
        getContentPane().add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 190, 30));

        tabelaVenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Prod.", "Nome Prod.", "Quantia", "Preço", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaVenda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 610, 350));

        jLabelTroco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTroco.setText("TROCO");
        getContentPane().add(jLabelTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTotal.setText("TOTAL");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 190, 30));
        getContentPane().add(txtPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 190, 30));

        txtExtrato.setColumns(20);
        txtExtrato.setRows(5);
        txtExtrato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtExtrato);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 290, 250));

        btnRealizarVenda.setBackground(new java.awt.Color(255, 255, 255));
        btnRealizarVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRealizarVenda.setText("Realizar Venda");
        btnRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 230, 40));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            code = Integer.parseInt(txtCod.getText());
            String sql = "select nome_produto, preco_venda from adm_produto where id_produto = ?";
            conn = new conexaoDAO().conectaBD();

            try {
                pstm = conn.prepareStatement(sql);
                pstm.setInt(1, code);
                rs = pstm.executeQuery();

                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                } else {
                    String nome, preco;
                    nome = rs.getString("nome_produto");
                    preco = rs.getString("preco_venda");

                    txtNome.setText(nome.trim());
                    txtPreco.setText(preco.trim());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "atn_vendasView - CodeKeyPressed: " + e);
            }
        }

    }//GEN-LAST:event_txtCodKeyPressed

    private void spnQntdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQntdStateChanged
        int qnt = Integer.parseInt(spnQntd.getValue().toString());
        double preco = Double.parseDouble(txtPreco.getText());

        double total = qnt * preco;

        txtValor.setText(String.valueOf(total));
    }//GEN-LAST:event_spnQntdStateChanged

    private void Troco() {

        double valor = Double.parseDouble(txtTotal.getText());
        double pagamento = Double.parseDouble(txtPagamento.getText());

        double totalv = pagamento - valor;

        txtTroco.setText(String.valueOf(totalv));

    }


    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel) tabelaVenda.getModel();
        model.addRow(new Object[]{
            txtCod.getText(),
            txtNome.getText(),
            spnQntd.getValue().toString(),
            txtPreco.getText(),
            txtValor.getText()

        });

        double soma = 0;

        for (int i = 0; i < tabelaVenda.getRowCount(); i++) {
            soma = soma + Double.parseDouble(tabelaVenda.getValueAt(i, 4).toString());
        }

        txtTotal.setText(Double.toString(soma));

        String dataSaida, prodSaida, quantSaida;
        dataSaida = txtData.getText();
        prodSaida = txtNome.getText();
        quantSaida = String.valueOf(spnQntd.getValue().toString());

        String sqlSaida = "Insert into adm_estsaida(data_est, prod_est, quant_est) values (?,?,?)";
        conn = new conexaoDAO().conectaBD();

        try {

            pstm = conn.prepareStatement(sqlSaida);
            pstm.setString(1, dataSaida);
            pstm.setString(2, prodSaida);
            pstm.setString(3, quantSaida);

            pstm.execute();
            pstm.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "atn_vendasVIEW: " + e);
        }

        String sqls = "Select quantidade_produto from adm_produto where id_produto = ?";
        conn = new conexaoDAO().conectaBD();

        try {
            pstm = conn.prepareStatement(sqls);
            pstm.setInt(1, code);
            rs = pstm.executeQuery();

            if (rs.next() == true) {

                cod = Integer.parseInt(rs.getString("quantidade_produto"));
                qntdS = Integer.parseInt(spnQntd.getValue().toString());

                total = String.valueOf(cod - qntdS);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "atn_vendasVIEW - : " + e);
        }

        String sql_ = "update adm_produto set quantidade_produto = ? where id_produto = ?";
        conn = new conexaoDAO().conectaBD();

        try {

            pstm = conn.prepareStatement(sql_);
            pstm.setString(1, total);
            pstm.setInt(2, code);
            pstm.execute();
            pstm.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "atn_vendas - Produto: " + e);
        }

        String nomevenda, valorvenda, quantvenda, datavenda;

        nomevenda = txtNome.getText();

        valorvenda = txtValor.getText();
        quantvenda = String.valueOf(spnQntd.getValue().toString());
        datavenda = txtData.getText();

        String sqladd = "insert into atn_vendas (valor_venda, prod_venda, quant_venda, data_venda ) values (?,?,?,?)";
        conn = new conexaoDAO().conectaBD();
        try {

            pstm = conn.prepareStatement(sqladd);
            pstm.setString(1, valorvenda);
            pstm.setString(2, nomevenda);
            pstm.setString(3, quantvenda);
            pstm.setString(4, datavenda);

            pstm.execute();
            pstm.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "atn_vendas - Vendas: " + e);
        }

        txtCod.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtValor.setText("");
        txtData.setText("");
        txtCod.requestFocus();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    public void Extrato() {

        String total = txtTotal.getText();
        String pag = txtPagamento.getText();
        String troco = txtTroco.getText();

        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel) tabelaVenda.getModel();

        txtExtrato.setText(txtExtrato.getText() + "*********************************************\n");
        txtExtrato.setText(txtExtrato.getText() + "*                     extratro               \n");
        txtExtrato.setText(txtExtrato.getText() + "*********************************************\n");
        txtExtrato.setText(txtExtrato.getText() + "Produto" + "\t" + "Preço" + "\t" + "Valor" + "\n");

        for (int i = 0; i < model.getRowCount(); i++) {

            String nomep = (String) model.getValueAt(i, 1);
            String price = (String) model.getValueAt(i, 3);
            String valor = (String) model.getValueAt(i, 4);

            txtExtrato.setText(txtExtrato.getText() + nomep + "\t" + price + "\t" + valor + "\n");
        }

        txtExtrato.setText(txtExtrato.getText() + "\n");
        txtExtrato.setText(txtExtrato.getText() + "\n");

        txtExtrato.setText(txtExtrato.getText() + "\t" + "\t" + "Subtotal:" + total + "\n");
        txtExtrato.setText(txtExtrato.getText() + "\t" + "\t" + "Pagamento:" + pag + "\n");
        txtExtrato.setText(txtExtrato.getText() + "\t" + "\t" + "Troco:" + troco + "\n");

        txtExtrato.setText(txtExtrato.getText() + "*********************************************\n");
        txtExtrato.setText(txtExtrato.getText() + "*                     Volte Novamente!       \n");
        txtExtrato.setText(txtExtrato.getText() + "*********************************************\n");
    }

    private void btnRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVendaActionPerformed
        Troco();
        Extrato();

        vt = txtTotal.getText();
        dt = txtData.getText();

        controleCaixa();


    }//GEN-LAST:event_btnRealizarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atn_vendasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atn_vendasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atn_vendasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atn_vendasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atn_vendasVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_dados;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRealizarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPagamento;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTroco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spnQntd;
    private javax.swing.JTable tabelaVenda;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextArea txtExtrato;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPagamento;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void controleCaixa() {

        String usuario;

        LoginVIEW objlogin = new LoginVIEW();

        usuario = objlogin.user;

        String sql = "Insert into adm_control(data_control, tipo_control, descricao_control, valor_control, funcionario_control) values(?,?,?,?,?)";
        conn = new conexaoDAO().conectaBD();

        try {

            pstm = conn.prepareStatement(sql);

            pstm.setString(1, dt);
            pstm.setString(2, "Entrada");
            pstm.setString(3, "Vendas");
            pstm.setString(4, vt);
            pstm.setString(5, usuario);

            pstm.execute();
            pstm.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "atn_vendasVIEW - controleCaixa: " + e);
        }

    }

}
